export const ERROR_TYPES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    SEND_MAIL_ERROR: 'SEND_MAIL_ERROR',
    MS_AUTH_ERROR: 'MS_AUTH_ERROR'
};